-- Lote 1: Receitas 8-15 (8 receitas)

-- Recipe 8
INSERT INTO public.recipes (title, description, image_url, prep_time_minutes, serves_people, calories_normal, calories_fit, ingredients, preparation_full, preparation_steps, category, tags, allergens, is_active)
VALUES ('Wrap de Frango Desfiado com Abacate', 'Wrap leve e nutritivo, perfeito para o almoço. Rico em proteínas e gorduras boas!', 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800', 20, 2, 450, 280, '[{"item": "Peito de frango cozido", "quantity": "200g", "notes": "desfiado"}, {"item": "Tortilha integral", "quantity": "2 unidades", "notes": "pode usar wrap fit"}, {"item": "Abacate", "quantity": "1 unidade", "notes": "amassado"}, {"item": "Tomate", "quantity": "1 unidade", "notes": "fatiado"}, {"item": "Alface", "quantity": "4 folhas", "notes": null}, {"item": "Iogurte grego", "quantity": "3 colheres", "notes": null}, {"item": "Limão", "quantity": "1/2 unidade", "notes": "para o suco"}, {"item": "Temperos", "quantity": "a gosto", "notes": "sal, pimenta, cominho"}]', 'Desfie o frango e tempere com sal, pimenta e cominho. Amasse o abacate com limão. Aqueça as tortilhas. Espalhe o abacate, adicione alface, tomate, frango e finalize com iogurte grego. Enrole bem apertado.', '[{"step": 1, "title": "Prepare o frango", "description": "Desfie o frango cozido e tempere com sal, pimenta e cominho.", "time_minutes": 5}, {"step": 2, "title": "Faça o guacamole", "description": "Amasse o abacate com suco de limão até formar um creme.", "time_minutes": 5}, {"step": 3, "title": "Monte o wrap", "description": "Espalhe o abacate na tortilha, adicione alface, tomate e frango.", "time_minutes": 5}, {"step": 4, "title": "Finalize", "description": "Adicione iogurte grego e enrole bem apertado.", "time_minutes": 5}]', 'Almoço', ARRAY['fit', 'proteína', 'gordura boa', 'prático'], ARRAY['glúten', 'laticínios'], TRUE);

-- Recipe 9
INSERT INTO public.recipes (title, description, image_url, prep_time_minutes, serves_people, calories_normal, calories_fit, ingredients, preparation_full, preparation_steps, category, tags, allergens, is_active)
VALUES ('Chips de Batata Doce Crocante', 'Snack saudável e crocante! Muito melhor que batata frita tradicional.', 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800', 40, 4, 320, 135, '[{"item": "Batata doce", "quantity": "2 unidades médias", "notes": "cortadas bem finas"}, {"item": "Azeite", "quantity": "2 colheres de sopa", "notes": null}, {"item": "Páprica doce", "quantity": "1 colher de chá", "notes": null}, {"item": "Alecrim seco", "quantity": "1 colher de chá", "notes": null}, {"item": "Sal marinho", "quantity": "a gosto", "notes": null}]', 'Pré-aqueça o forno a 200°C. Corte a batata doce em fatias bem finas (use mandolina se tiver). Misture com azeite e temperos. Disponha em assadeira forrada com papel manteiga sem sobrepor. Asse por 30-35 minutos, virando na metade.', '[{"step": 1, "title": "Corte as batatas", "description": "Corte as batatas doce em fatias bem finas e uniformes (2-3mm).", "time_minutes": 10}, {"step": 2, "title": "Tempere", "description": "Misture as fatias com azeite, páprica, alecrim e sal.", "time_minutes": 5}, {"step": 3, "title": "Asse", "description": "Disponha em assadeira sem sobrepor e asse a 200°C por 15 minutos.", "time_minutes": 15}, {"step": 4, "title": "Vire e finalize", "description": "Vire as fatias e asse por mais 15-20 minutos até ficarem crocantes.", "time_minutes": 20}]', 'Lanches', ARRAY['fit', 'crocante', 'snack', 'sem glúten'], ARRAY[], TRUE);

-- Recipe 10
INSERT INTO public.recipes (title, description, image_url, prep_time_minutes, serves_people, calories_normal, calories_fit, ingredients, preparation_full, preparation_steps, category, tags, allergens, is_active)
VALUES ('Mousse de Chocolate com Abacate', 'Sobremesa cremosa e saudável! Sim, tem abacate e você não vai sentir!', 'https://images.unsplash.com/photo-1541599468348-e96984315921?w=800', 10, 4, 380, 165, '[{"item": "Abacate maduro", "quantity": "2 unidades", "notes": "bem maduro"}, {"item": "Cacau em pó 100%", "quantity": "1/3 xícara", "notes": null}, {"item": "Adoçante", "quantity": "1/3 xícara", "notes": "xilitol ou eritritol"}, {"item": "Leite de coco", "quantity": "1/4 xícara", "notes": null}, {"item": "Essência de baunilha", "quantity": "1 colher de chá", "notes": null}, {"item": "Cacau nibs", "quantity": "2 colheres", "notes": "para decorar"}]', 'Bata todos os ingredientes no liquidificador até ficar bem cremoso e homogêneo. Prove e ajuste o adoçante se necessário. Distribua em tacinhas e leve à geladeira por pelo menos 2 horas. Decore com cacau nibs.', '[{"step": 1, "title": "Bata tudo", "description": "No liquidificador, bata abacate, cacau, adoçante, leite de coco e baunilha até cremoso.", "time_minutes": 5}, {"step": 2, "title": "Ajuste o sabor", "description": "Prove e ajuste o adoçante se necessário.", "time_minutes": 2}, {"step": 3, "title": "Gelar", "description": "Distribua em tacinhas e leve à geladeira por 2 horas.", "time_minutes": 120}]', 'Sobremesas', ARRAY['fit', 'chocolate', 'sem açúcar', 'vegano'], ARRAY[], TRUE);

-- Recipe 11
INSERT INTO public.recipes (title, description, image_url, prep_time_minutes, serves_people, calories_normal, calories_fit, ingredients, preparation_full, preparation_steps, category, tags, allergens, is_active)
VALUES ('Bowl de Açaí Proteico', 'Açaí cremoso sem xarope! Com proteína e toppings saudáveis.', 'https://images.unsplash.com/photo-1590846406792-0adc7f938f1d?w=800', 10, 2, 520, 280, '[{"item": "Polpa de açaí congelada", "quantity": "200g", "notes": "sem açúcar"}, {"item": "Banana congelada", "quantity": "1 unidade", "notes": null}, {"item": "Whey protein", "quantity": "1 scoop", "notes": "sabor neutro ou cacau"}, {"item": "Leite vegetal", "quantity": "100ml", "notes": "apenas para soltar"}, {"item": "Granola fit", "quantity": "3 colheres", "notes": null}, {"item": "Banana fatiada", "quantity": "1/2 unidade", "notes": null}, {"item": "Pasta de amendoim", "quantity": "1 colher", "notes": null}, {"item": "Frutas vermelhas", "quantity": "a gosto", "notes": null}]', 'Bata a polpa de açaí, banana congelada e whey com um pouco de leite até ficar cremoso (consistência de sorvete). Despeje em uma tigela e decore com granola, banana, pasta de amendoim e frutas vermelhas.', '[{"step": 1, "title": "Bata o açaí", "description": "No liquidificador, bata açaí, banana e whey com pouco leite até cremoso.", "time_minutes": 5}, {"step": 2, "title": "Monte o bowl", "description": "Despeje em tigela e decore com granola, frutas e pasta de amendoim.", "time_minutes": 5}]', 'Café da Manhã', ARRAY['fit', 'proteína', 'energético', 'sem lactose'], ARRAY[], TRUE);

-- Recipe 12
INSERT INTO public.recipes (title, description, image_url, prep_time_minutes, serves_people, calories_normal, calories_fit, ingredients, preparation_full, preparation_steps, category, tags, allergens, is_active)
VALUES ('Hambúrguer Vegano de Grão de Bico', 'Hambúrguer plant-based delicioso! Rico em proteínas e fibras.', 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=800', 30, 4, 410, 215, '[{"item": "Grão de bico cozido", "quantity": "2 xícaras", "notes": null}, {"item": "Aveia em flocos", "quantity": "1/2 xícara", "notes": null}, {"item": "Cebola", "quantity": "1 unidade pequena", "notes": "picada"}, {"item": "Alho", "quantity": "2 dentes", "notes": "amassados"}, {"item": "Cominho", "quantity": "1 colher de chá", "notes": null}, {"item": "Páprica", "quantity": "1 colher de chá", "notes": null}, {"item": "Salsinha", "quantity": "1/4 xícara", "notes": "picada"}, {"item": "Sal e pimenta", "quantity": "a gosto", "notes": null}]', 'Amasse o grão de bico com um garfo (deixe alguns pedaços). Adicione aveia, cebola, alho, temperos e salsinha. Misture bem. Molde 4 hambúrgueres. Grelhe em frigideira com um fio de azeite por 5 minutos de cada lado.', '[{"step": 1, "title": "Prepare a massa", "description": "Amasse o grão de bico e misture com aveia, cebola, alho e temperos.", "time_minutes": 10}, {"step": 2, "title": "Molde os hambúrgueres", "description": "Divida em 4 porções e molde hambúrgueres de tamanho uniforme.", "time_minutes": 5}, {"step": 3, "title": "Grelhe", "description": "Aqueça frigideira com azeite e grelhe por 5 min de cada lado.", "time_minutes": 15}]', 'Almoço', ARRAY['fit', 'vegano', 'proteína vegetal', 'sem glúten'], ARRAY['aveia'], TRUE);

-- Recipe 13
INSERT INTO public.recipes (title, description, image_url, prep_time_minutes, serves_people, calories_normal, calories_fit, ingredients, preparation_full, preparation_steps, category, tags, allergens, is_active)
VALUES ('Parfait de Iogurte com Chia', 'Café da manhã prático em potinho! Prepare na noite anterior.', 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=800', 10, 2, 340, 190, '[{"item": "Iogurte grego natural", "quantity": "2 potes", "notes": "desnatado"}, {"item": "Sementes de chia", "quantity": "3 colheres de sopa", "notes": null}, {"item": "Frutas vermelhas", "quantity": "1 xícara", "notes": null}, {"item": "Granola fit", "quantity": "4 colheres", "notes": null}, {"item": "Mel", "quantity": "1 colher de sopa", "notes": "opcional"}]', 'Em potes de vidro, faça camadas alternando iogurte, chia, frutas e granola. Finalize com um fio de mel. Tampe e leve à geladeira por pelo menos 4 horas (ideal overnight). A chia vai hidratar e formar um gel.', '[{"step": 1, "title": "Monte as camadas", "description": "Em potes, alterne camadas de iogurte, chia, frutas e granola.", "time_minutes": 10}, {"step": 2, "title": "Gelar", "description": "Tampe e leve à geladeira por pelo menos 4 horas.", "time_minutes": 240}]', 'Café da Manhã', ARRAY['fit', 'prático', 'proteína', 'overnight'], ARRAY['laticínios'], TRUE);

-- Recipe 14
INSERT INTO public.recipes (title, description, image_url, prep_time_minutes, serves_people, calories_normal, calories_fit, ingredients, preparation_full, preparation_steps, category, tags, allergens, is_active)
VALUES ('Salmão Grelhado com Aspargos ao Alho', 'Jantar sofisticado e nutritivo! Rico em ômega-3.', 'https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800', 25, 2, 580, 340, '[{"item": "Filé de salmão", "quantity": "2 unidades (300g)", "notes": "com pele"}, {"item": "Aspargos", "quantity": "1 maço (250g)", "notes": null}, {"item": "Alho", "quantity": "4 dentes", "notes": "laminados"}, {"item": "Azeite", "quantity": "2 colheres de sopa", "notes": null}, {"item": "Limão", "quantity": "1 unidade", "notes": null}, {"item": "Sal e pimenta", "quantity": "a gosto", "notes": null}]', 'Tempere o salmão com sal, pimenta e limão. Grelhe com a pele para baixo por 4 minutos, vire e grelhe mais 3 minutos. Retire e reserve. Na mesma frigideira, refogue aspargos com alho e azeite por 5 minutos. Sirva o salmão sobre os aspargos.', '[{"step": 1, "title": "Tempere o salmão", "description": "Tempere os filés com sal, pimenta e suco de limão.", "time_minutes": 5}, {"step": 2, "title": "Grelhe o salmão", "description": "Grelhe com pele para baixo por 4 min, vire e grelhe mais 3 min.", "time_minutes": 10}, {"step": 3, "title": "Refogue os aspargos", "description": "Na mesma frigideira, refogue aspargos com alho por 5 minutos.", "time_minutes": 10}]', 'Jantar', ARRAY['fit', 'proteína', 'omega 3', 'low carb'], ARRAY['peixe'], TRUE);

-- Recipe 15
INSERT INTO public.recipes (title, description, image_url, prep_time_minutes, serves_people, calories_normal, calories_fit, ingredients, preparation_full, preparation_steps, category, tags, allergens, is_active)
VALUES ('Bolinho de Arroz Integral Assado', 'Aproveite sobras de arroz! Bolinhos crocantes e saudáveis.', 'https://images.unsplash.com/photo-1623428187969-5da2dcea5ebf?w=800', 30, 6, 290, 160, '[{"item": "Arroz integral cozido", "quantity": "2 xícaras", "notes": "sobras"}, {"item": "Ovos", "quantity": "2 unidades", "notes": null}, {"item": "Cenoura ralada", "quantity": "1 xícara", "notes": null}, {"item": "Queijo cottage", "quantity": "1/2 xícara", "notes": null}, {"item": "Cebola", "quantity": "1 unidade", "notes": "picada"}, {"item": "Salsinha", "quantity": "1/4 xícara", "notes": "picada"}, {"item": "Temperos", "quantity": "a gosto", "notes": "sal, pimenta"}]', 'Misture todos os ingredientes em uma tigela. Molde bolinhos pequenos e disponha em assadeira forrada com papel manteiga. Pincele com azeite. Asse a 200°C por 25 minutos, virando na metade.', '[{"step": 1, "title": "Prepare a massa", "description": "Misture arroz, ovos, cenoura, queijo, cebola, salsinha e temperos.", "time_minutes": 10}, {"step": 2, "title": "Molde os bolinhos", "description": "Molde bolinhos do tamanho de uma colher e disponha em assadeira.", "time_minutes": 10}, {"step": 3, "title": "Asse", "description": "Pincele com azeite e asse a 200°C por 25 minutos, virando na metade.", "time_minutes": 25}]', 'Lanches', ARRAY['fit', 'aproveitamento', 'assado', 'proteína'], ARRAY['ovos', 'laticínios'], TRUE);
